name: Build and Export Godot Web Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Step 2: Download and setup Godot
      - name: Download Godot
        run: |
          GODOT_URL="https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip"
          wget $GODOT_URL -O godot.zip
          mkdir -p godot
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.0-stable_linux.x86_64
        shell: bash

      # Step 3: Export the project for Web (HTML5)
      - name: Export Web Build
        run: |
          mkdir -p export/web
          ./godot/Godot_v4.0-stable_linux.x86_64 --headless --export-release "HTML5" export/web/index.html
        shell: bash

      # Step 4: Upload the exported Web files as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Web Export
          path: export/web/
