name: Build and Export Godot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, mac, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Godot
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Exported Project - ${{ matrix.platform }}
          path: ${{ steps.export.outputs.archive_directory }}/*
